test/style/feat: Refactored several files:
feredean/node-api-starter pull request #20
Opened 2019-11-05 11:56 UTC by ajago

Hey, I am a developer moving from Java to Node right now, so looking to get a bit more experience of apps like this in Javascript. 
Am happy to split this into several PRs if needed, but thought it would be easier to handle it as one PR to start off with. I can create separate PRs for elements you are happy with if you dont want to take all the changes.

- Upload controller now processes upload in parallel
- Express config - uses es6 functions and optmised cors logic
- Secrets - all missing secrets are now logged out, minor tweak to mongoURI so it can be a constant
- Middleware - removed unnecessary brackets
- Integration tests - tidied up beforeEach and afterAll calls

2019-11-05 13:40 UTC, feredean commented
Thank you so much for contributing to this project! I'll be back with feedback shortly.

2019-11-05 14:20 UTC, feredean requested changes

2019-11-05 14:20 UTC, feredean commented on src/config/express.ts
>              callback(null, match);
The callback takes as parameters `(err: Error | null, allow?: boolean)` see https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/cors/index.d.ts#L11, as such this won't work. You can test it by installing the frontend as well https://github.com/feredean/node-api-starter-angular-app

You can either go with:
```ts
const match = origin.match(new RegExp(CORS_REGEX)) ? true : false;
```
or
```ts
callback(null, !!match);
```
I'm fine with both

2019-11-05 14:20 UTC, feredean commented on test/integration/integration.test.ts
Please also change line 73, 380 and 401 for consistency

2019-11-05 14:20 UTC, feredean commented on src/middleware/index.ts
> +        req.user = await jwt.verify(token, SESSION_SECRET) as Express.User;
While looking into this change I noticed that the `jwt.verify` function is not async https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/jsonwebtoken/index.d.ts#L162. This means several changes are required. 
1. both `isAuthenticated` and `hasPermission` middlewares don't need to be async
2. as a result the middleware tests also no longer need to be async

I can update this in a future PR or if you want, you can commit these changes in this one

2019-11-05 22:46 UTC, ajago commented on src/config/express.ts
>              callback(null, match);
ah good point

2019-11-05 22:46 UTC, ajago commented on test/integration/integration.test.ts
👍

2019-11-05 22:46 UTC, ajago commented on src/middleware/index.ts
> +        req.user = await jwt.verify(token, SESSION_SECRET) as Express.User;
I'll have a look at this tomorrow

2019-11-06 10:51 UTC, ajago commented
addressed all the changes now

2019-11-06 12:43 UTC, feredean commented
Looking good! One final thing, please rebase and squash everything into a single commit to keep the commit history clean

2019-11-06 15:55 UTC, ajago commented
Was going to ask about your preference on that. Done.

2019-11-06 16:28 UTC, feredean approved these changes

2019-11-06 16:29 UTC, merged

2019-11-06 16:33 UTC, feredean commented
Thank you very much for your contribution!

2019-11-07 09:31 UTC, feredean commented
@ajago forgot to mention, if you're new to node you should take a look at these two projects
https://docs.nestjs.com/
https://typeorm.io/
I found them very interesting and they might become part of this project in the future

2019-11-11 09:54 UTC, ajago commented
Thanks for the message, I've had a look at nestjs and it seems to be trying to introduce the same level of magic that you get in the Java Spring world, so will be interesting to see how it develops.